name: CI

on:
  push:
    branches: [main, nightly]
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    uses: thenoetrevino/github/.github/workflows/nvim-plugins-ci.yml@main
    secrets: inherit
    with:
      plugin: dadbod-ui.nvim
      repo: TheNoeTrevino/dadbod-ui.nvim
